### ISSUE TITLE
Questions about this repo from a curious folk.

### ISSUE THREAD

**Issue by deckarep** [ekatz/sci#1]
Hi, 

What an awesome implementation of the Sierra Creative Interpreter! 

While it looks like this repo hasn't had updates in awhile I was hoping you can offer up some basic insights into of how you are building this and what's the intention?

I have a few questions that I'd possibly like to ask:

1.  How feature complete is this? Is it capable of running any particular games?  
2.  It looks like it supports Windows only? Although I do see some references to building for iOS?
3.  What did you reference to build this? I know there are various docs outlining how the PMachine works and memory model. But also there are other possibilities like ScummVM and the original source code which has now been posted to Github.
4.  Which engine is this? SCI16 or 32?
5.  Are you still maintaining this or do you have plans to update it?
6.  I noticed some LLVM wizardry as well? Were you planning on doing static recompilation of the engine so that it can run natively on the latest hardware? How far did you get on that?

I know there's a lot of questions here and I'd love to know more simply because I'm curious and because I've long considered trying to build a re-implementation of the SCI engine myself but from my perspective it's a *significant* under-taking.  Your code might be a good starting point to pick up this work or possibly reference depending on what your intentions are at this point.

Bravo for writing some really nice code!

**Comment by ekatz** [comment]
Hi,
Thanks for the interest in the code.
I reverse engineered the SCI16 binary for Windows, specifically the one used in "Jones in the Fast Lane". I used the already available original copy of the source code for reference, especially for naming purposes; so the resulting code would be as close as possible to the original.

Regarding your questions:
1. This is the version used in the Windows implementation of "Jones in the Fast Lane". That is it. Not sure about specific features, but I can only say that there are some differences in the PMachine implementation between different versions, especially between DOS and Windows.
2. This has been tested on Windows and iOS. Works perfectly on both of them. Just remember that this is a very close implementation to the original source code, so it is not very efficient on a modern OS.
3. As I wrote above, this is a new implementation based on reverse engineering the binary.
4. SCI16 for Windows; "Jones in the Fast Lane" implementation.
5. I have no real intention to work on this project any further, but if you want to contribute, then you are welcome!
6. The LLVM part is for statically compile the game scripts AOT, and by that removing the JIT PMachine. This was done just for fun, utilizing my experience as a Compiler Engineer.

Cheers,
Ehud

**Comment by deckarep** [comment]
@ekatz - hey I really appreciate the time you took to respond to this! What an impressive accomplishment. 

I’ll see if I can get it building as a starting point. 

One last question: you mentioned this is a straight port so it’s not efficient on modern hardware. But is this implementation able to run the game at full speed? I don’t think Sierra games are super taxing on hardware anyways so maybe this implementation is good enough in terms of performance.

**Comment by ekatz** [comment]
Because this is an exact implementation, the event loop and the game's speed is scheduled as in DOS. This has dependencies of the exact time an assembly instruction takes to execute. The game's event loop is implemented in the game scripts, and are actually just querying in a sleepless loop, the states of the game (and inputs) and updates the graphics. In modern CPUs this is **way** too fast! To solve this, I have added several calls to "sleep", in certain places.
I guess the best solution is to rewrite the event loop, and make it an actual even driven loop. The problem is that it is too intrusive, and game-dependent.
